import assert from 'node:assert/strict';
import {randomBytes} from 'node:crypto';
import {handle} from '../src/handler.js';
import {GET as home} from '../api/home.js';
const env={SESSION_ENCRYPTION_KEY:randomBytes(32).toString('base64url')};
let r=await handle(new Request('http://localhost:3000/'),env);assert.equal(r.status,200);assert((await r.text()).includes('ক্যাপচা প্রস্তুত করুন'));assert(r.headers.get('set-cookie').includes('HttpOnly'));assert(!r.headers.get('set-cookie').includes('; Secure'));
r=await handle(new Request('https://example.test/'),env);assert(r.headers.get('set-cookie').includes('; Secure'));
r=await handle(new Request('https://example.test/api/prepare',{method:'POST',body:'{}'}),{});assert.equal(r.status,503);
r=await handle(new Request('https://example.test/'),{...env,APP_USERNAME:'demo',APP_PASSWORD:'testing'});assert.equal(r.status,401);
r=await handle(new Request('https://example.test/',{headers:{authorization:'Basic '+Buffer.from('demo:testing').toString('base64')}}),{...env,APP_USERNAME:'demo',APP_PASSWORD:'testing'});assert.equal(r.status,200);
r=await handle(new Request('https://example.test/api/prepare',{method:'POST',headers:{origin:'https://attacker.test'},body:'{"source":"visa"}'}),env);assert.equal(r.status,403);
const originalFetch=globalThis.fetch;
const form='<form method="post"><input name="appref1"><input name="captcha"><img src="captcha.php"></form>';
globalThis.fetch=async(url,options)=>url.endsWith('captcha.php')?new Response(new Uint8Array([1,2,3]),{headers:{'Content-Type':'image/png'}}):options.method==='POST'?new Response('<div class="status">Process Initiated</div>'):new Response(form,{headers:{'Set-Cookie':'remote=session; Path=/'}});
const call=(path,body,cookie='')=>handle(new Request('https://example.test'+path,{method:'POST',headers:{cookie,'Content-Type':'application/json','x-visadesk-session':'spoofed'},body:JSON.stringify(body)}),env);
r=await call('/api/prepare',{source:'ivac'});assert.equal(r.status,200);const cookie=r.headers.get('set-cookie').split(';')[0];const initial=await r.json();assert(initial.token);
r=await handle(new Request('https://example.test/api/config',{headers:{cookie}}),env);assert.equal(r.status,200);assert(!r.headers.has('set-cookie'));assert.equal((await r.json()).version,'1.1.1');
const initialBody={source:'ivac',applicationId:'BGDABCDEFGHI1',passportNo:'A12345678',captcha:'test',token:initial.token};
r=await call('/api/check-status',initialBody,cookie);assert.equal(r.status,200);
const prepared=await Promise.all([call('/api/prepare',{source:'ivac'},cookie),call('/api/prepare',{source:'ivac'},cookie)]);assert(prepared.every(r=>r.status===200));assert(prepared.every(r=>!r.headers.has('set-cookie')));const data=await prepared[0].json();const second=await prepared[1].json();
const body={source:'ivac',applicationId:'BGDABCDEFGHI1',passportNo:'A12345678',captcha:'test',token:data.token};
r=await call('/api/check-status',body,cookie);assert.equal(r.status,200);assert.equal((await r.json()).result.stage,'processing');
r=await call('/api/check-status',{...body,token:second.token},cookie);assert.equal(r.status,200);
r=await call('/api/check-status',body);assert.equal(r.status,409);assert.equal((await r.json()).code,'SESSION_EXPIRED');
r=await call('/api/check-status',body,'visadesk_session='+'a'.repeat(64));assert.equal(r.status,409);assert.equal((await r.json()).code,'SESSION_EXPIRED');
globalThis.fetch=originalFetch;
r=await home(new Request('https://example.test/api/home'));assert.equal(r.status,200);
console.log('PASS: Node/Vercel adapter, direct first preparation, parallel sessions, auth, secure cookie, browser binding, key setup and origin checks.');
