import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
const html=await readFile(new URL('../src/index.html',import.meta.url),'utf8');
const ids=[...html.split('<script')[0].matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(ids.length,new Set(ids).size);
assert(!html.includes('historySection'));assert(!html.includes('rememberPassport'));assert(!html.includes('OCR.space'));assert(!html.includes('মূল সাইটে দেখুন'));assert(!html.includes('নতুন আবেদন'));assert(!html.includes('AI Vision'));
const elements={},removed=[],writes=[],calls=[],drawn=[],downloads=[],operationStates=[],reads=[],documentListeners={};const storage=new Map([['visadesk.recentInputs',JSON.stringify([{applicationId:'BGDRECENT001',passportNo:'Z11223344',status:'should not be kept'},{applicationId:'<script>',passportNo:'oops'}])]]);let canvasSize;const fakeContext={font:'',fillStyle:'',scale(){},beginPath(){},roundRect(){},fill(){},fillText(text){drawn.push(text);},measureText(text){return {width:text.length*12};}};let visaStage='granted_printed',rejectVisa=false,visaError=null,ocrExpired=false,configFail=false;
function element(id){const classes=new Set();const e={dataset:{},style:{},attributes:{},textContent:'',value:'',type:id==='passportNo'?'password':'text',listeners:{},classList:{add(k){classes.add(k);},remove(...keys){for(const k of keys)classes.delete(k);},toggle(k,v){if(v??!classes.has(k))classes.add(k);else classes.delete(k);},contains:k=>classes.has(k)},addEventListener(event,fn){this.listeners[event]=fn;},setAttribute(k,v){this.attributes[k]=v;},contains(target){return ['applicationId','passportNo','clearRecents','recentSuggestionsList'].some(k=>elements[k]===target);},scrollIntoView(){},focus(){},reset(){elements.applicationId.value='';elements.passportNo.value='';},querySelectorAll(){return Object.entries(elements).filter(([k])=>k.startsWith('code-')||['applicationId','passportNo','checkBtn','confirmBtn'].includes(k)).map(([,v])=>v);}};
 Object.defineProperty(e,'innerHTML',{get(){return this.markup||'';},set(value){this.markup=value;for(const m of value.matchAll(/\bid="([^"]+)"/g))elements[m[1]]=element(m[1]);}});return e;}
for(const id of ids)elements[id]=element(id);
const context=vm.createContext({document:{addEventListener(event,fn){documentListeners[event]=fn;},fonts:{ready:Promise.resolve()},body:{dataset:{},appendChild(){}},createElement(tag){if(tag==='canvas'){const canvas={getContext:()=>fakeContext,toBlob(callback,type){canvasSize={width:this.width,height:this.height,type};callback(new Blob(['png'],{type}));}};return canvas;}if(tag==='a')return {click(){downloads.push({href:this.href,filename:this.download});},remove(){}};throw new Error('Unexpected element');},getElementById:id=>elements[id]||null},window:{matchMedia:()=>({matches:true})},localStorage:{removeItem:k=>{removed.push(k);storage.delete(k);},setItem:(k,v)=>{writes.push([k,v]);storage.set(k,v);},getItem:k=>{reads.push(k);return storage.get(k)??null;}},setTimeout:(fn,delay)=>delay===30000?setTimeout(fn,0):setTimeout(fn,delay),clearTimeout,URL:{createObjectURL:()=> 'blob:test-results',revokeObjectURL(){}},console,AbortController,fetch:async(path,options)=>{
 const body=options.body?JSON.parse(options.body):null;calls.push({path,body,options});operationStates.push({path,visible:!elements.operationPanel.classList.contains('hidden'),percent:elements.operationTrack.attributes['aria-valuenow'],busy:elements.confirmBtn.disabled});
 if(path==='/api/config')return configFail?new Response('unavailable',{status:503}):Response.json({version:'1.1.1'});
 if(path==='/api/prepare')return Response.json({token:'test-session',expiresAt:Date.now()+300000,captcha:'data:image/png;base64,iVBORw=='});
 if(path==='/api/read-captcha')return ocrExpired&&body.source==='visa'?Response.json({code:'SESSION_EXPIRED',needsNewCaptcha:true,error:'expired'},{status:409}):Response.json({text:'abcdef',ready:true,engine:'ocr-space'});
 if(path==='/api/check-status'){
  if(body.source==='visa'&&rejectVisa)return Response.json({error:'Invalid captcha'},{status:400});
  if(body.source==='visa'&&visaError)return visaError.html?new Response('<h1>FUNCTION_INVOCATION_TIMEOUT</h1>',{status:504}):Response.json(visaError,{status:visaError.status||503});
  return Response.json({result:{stage:body.source==='visa'?visaStage:'ready',label:body.source==='visa'?(visaStage==='granted_not_printed'?'Granted but Not-Printed':'Granted and Printed'):'Ready For Delivery',checkedAt:new Date().toISOString(),deliverySteps:body.source==='ivac'?['Received At Center','Process Initiated','Ready For Delivery','Delivered From Center'].map((label,i)=>({label,done:i<3})):null}});
 }
 throw new Error('Unexpected request');
}});
vm.runInContext(html.match(/<script>([\s\S]*?)<\/script>/)[1],context);
assert.equal(vm.runInContext("normalizeCaptchaText('visa',' A bC1 23\\n')",context),'AbC123');assert.equal(vm.runInContext("normalizeCaptchaText('ivac',' AbCd ')",context),'abcd');
assert.equal(elements.themeLabel.textContent,'দিনের মোড');assert.equal(elements.themeToggle.attributes['aria-pressed'],'true');elements.themeToggle.onclick();assert.equal(elements.themeLabel.textContent,'নাইট মোড');assert.equal(elements.themeToggle.attributes['aria-pressed'],'false');elements.themeToggle.onclick();assert.equal(elements.themeToggle.attributes['aria-pressed'],'true');
assert.deepEqual(reads,['visadesk.recentInputs']);elements.applicationId.listeners.focus();assert(elements.recentSuggestionsList.innerHTML.includes('BGDRECENT001'));assert(elements.recentSuggestionsList.innerHTML.includes('Z11223344'));assert(!elements.recentSuggestionsList.innerHTML.includes('should not be kept'));assert(!elements.recentSuggestions.classList.contains('hidden'));const beforeSelection=calls.length;elements.recentSuggestionsList.listeners.click({target:{closest:selector=>selector==='[data-recent]'?{dataset:{recent:'0'}}:null}});assert.equal(elements.applicationId.value,'BGDRECENT001');assert.equal(elements.passportNo.value,'Z11223344');assert.equal(calls.length,beforeSelection);assert(elements.recentSuggestions.classList.contains('hidden'));
const event={preventDefault(){}};const checkCount=()=>calls.filter(c=>c.path==='/api/check-status').length;
async function start(){elements.applicationId.value='BGDABCDEFGHI1';elements.passportNo.value='A12345678';await elements.trackingForm.listeners.submit(event);}
assert.deepEqual(removed,['visadesk.records','visadesk.history']);assert.equal(elements.app.dataset.phase,'entry');assert.equal(checkCount(),0);assert.equal(elements.saveResults.disabled,true);
await start();assert.equal(elements.app.dataset.phase,'review');assert.equal(checkCount(),0);assert.equal(writes.length,0);assert.equal(elements['code-visa'].value,'abcdef');assert(elements['captcha-visa'].innerHTML.includes('<img'));assert(!elements.reviewStage.classList.contains('hidden'));assert.equal(elements.confirmBtn.disabled,false);assert.equal(elements.operationFill.style.width,'100%');assert.equal(elements.operationCount.textContent,'৪ / ৪ কাজ');assert(operationStates.filter(s=>s.path==='/api/prepare'||s.path==='/api/read-captcha').every(s=>s.visible));assert(operationStates.some(s=>s.path==='/api/read-captcha'&&Number(s.percent)>0&&Number(s.percent)<100));
assert.equal(calls[0].path,'/api/prepare');assert(!calls.some(c=>c.path==='/api/config'));assert(calls.every(c=>c.options.credentials==='same-origin'&&c.options.cache==='no-store'));assert(elements['captcha-visa'].innerHTML.includes('autocapitalize="off"'));
elements['code-visa'].value='AbC123';await elements.captchaForm.listeners.submit(event);assert.equal(checkCount(),2);assert.equal(JSON.parse(storage.get('visadesk.recentInputs'))[0].applicationId,'BGDABCDEFGHI1');assert.equal(calls.find(c=>c.path==='/api/check-status'&&c.body.source==='visa').body.captcha,'AbC123');assert.equal(elements.app.dataset.phase,'result');assert.equal(elements.operationCount.textContent,'২ / ২ কাজ');assert.equal(elements.operationFill.style.width,'100%');assert(operationStates.filter(s=>s.path==='/api/check-status').every(s=>s.visible));assert(elements.introHero.classList.contains('hidden'));assert(elements.flowSteps.classList.contains('hidden'));assert.equal(elements.saveResults.disabled,false);await elements.saveResults.onclick();assert.equal(downloads.length,1);assert.equal(downloads[0].filename,'VisaDesk-BGDABCDEFGHI1.png');assert.equal(canvasSize.width,1800);assert.equal(canvasSize.type,'image/png');assert(canvasSize.height>1000);assert(drawn.some(t=>t.includes('ভিসা অনুমোদিত')));assert(drawn.includes('Ready For Delivery'));assert(drawn.includes('৭৫%'));assert(drawn.includes('৩ / ৪ ধাপ সম্পন্ন'));assert(!drawn.some(t=>t.includes('A12345678')));assert.equal(elements.saveResults.disabled,false);
assert(elements.visaResult.innerHTML.includes('ভিসা অনুমোদিত ও প্রিন্ট সম্পন্ন'));assert(elements.visaResult.innerHTML.includes('SMS না এলেও'));assert(elements.ivacResult.innerHTML.includes('৭৫%'));assert(elements.ivacResult.innerHTML.includes('delivery-milestones'));assert(elements.ivacResult.innerHTML.includes('অপেক্ষায়'));assert(elements.ivacResult.innerHTML.includes('পাসপোর্ট সংগ্রহ করা যাবে'));for(const source of ['visa','ivac']){const meanings=vm.runInContext('statusMeaning.'+source,context);for(const [stage,info] of Object.entries(meanings)){assert(/[\u0980-\u09ff]/.test(info.title),stage);assert(info.meaning.length>20,stage);}}assert.equal((elements.ivacResult.innerHTML.match(/>সম্পন্ন</g)||[]).length,3);
// The percentage always comes from confirmed source rows, including every
// supported step. The current completed milestone remains green and highlighted.
const originalIvac=vm.runInContext('JSON.stringify(current.ivac)',context);
for(let done=1;done<=4;done++){
 vm.runInContext(`current.ivac.stage=deliveryStages[${done-1}];current.ivac.deliverySteps=deliveryLabels.map((label,i)=>({label,done:i<${done}}));renderResult('ivac');`,context);
 const markup=elements.ivacResult.innerHTML;
 assert(markup.includes('aria-valuenow="'+done*25+'"'));
 assert(markup.includes('width:'+done*25+'%'));
 assert(markup.includes(done.toLocaleString('bn-BD')+' / ৪ ধাপ সম্পন্ন'));
 assert.equal((markup.match(/aria-current="step"/g)||[]).length,1);
 assert(markup.includes('done current'));
 assert(markup.includes('<ol class="delivery-step-cards"'));
 assert.equal((markup.match(/<li class="delivery-step-card /g)||[]).length,4);
 assert(!markup.includes('<details'));
 assert(markup.indexOf('delivery-step-cards')>markup.indexOf('progress-track'));
 assert.equal((markup.match(/class="delivery-badge done"/g)||[]).length,done);
 if(done===2){assert(markup.includes('পরের ধাপ: সংগ্রহের জন্য প্রস্তুত'));assert(markup.includes('পাসপোর্ট হস্তান্তরের অপেক্ষায়'));assert(!markup.includes('পাসপোর্ট দেওয়া হয়েছে'));}
 if(done===4){assert(markup.includes('all-complete'));assert(markup.includes('চারটি ধাপই সম্পন্ন হয়েছে'));assert(!markup.includes('পরের ধাপ:'));}
}
vm.runInContext('current.ivac='+originalIvac+';renderResult("ivac");',context);
assert(drawn.includes('গ্রহণ'));assert(drawn.includes('প্রক্রিয়া'));assert(drawn.includes('প্রস্তুত'));assert(drawn.includes('হস্তান্তর'));
vm.runInContext('current.ivac.deliverySteps[0].done="yes";renderResult("ivac");',context);assert(!elements.ivacResult.innerHTML.includes('role="progressbar"'));assert(!elements.ivacResult.innerHTML.includes('delivery-percentage'));assert(!elements.ivacResult.innerHTML.includes('class="delivery-badge done"'));assert(elements.ivacResult.innerHTML.includes('তথ্য নেই'));drawn.length=0;await elements.saveResults.onclick();assert(!drawn.includes('৭৫%'));vm.runInContext('current.ivac='+originalIvac+';',context);
vm.runInContext("current.ivac.deliverySteps=null;renderResult('ivac');",context);assert(!elements.ivacResult.innerHTML.includes('৭৫%'));drawn.length=0;await elements.saveResults.onclick();assert(!drawn.includes('৭৫%'));assert(!drawn.some(text=>text.includes('ধাপ সম্পন্ন')));
elements.newApplication.onclick();visaStage='granted_not_printed';await start();let n=checkCount();vm.runInContext('sessions.visa.expiresAt=0',context);await elements.captchaForm.listeners.submit(event);assert.equal(checkCount(),n);assert.equal(elements.app.dataset.phase,'review');assert(elements.reviewFeedback.textContent.includes('সময় শেষ'));await elements.captchaForm.listeners.submit(event);
assert(elements.visaResult.innerHTML.includes('ভিসা অনুমোদিত, প্রিন্ট হয়নি'));assert(!elements.visaResult.innerHTML.includes('SMS না এলেও'));
elements.newApplication.onclick();rejectVisa=true;await start();await elements.captchaForm.listeners.submit(event);n=checkCount();assert(elements.visaResult.innerHTML.includes('ক্যাপচা মিলিয়ে'));await elements.retryCaptcha.onclick();assert.equal(checkCount(),n);assert.equal(elements.app.dataset.phase,'review');rejectVisa=false;await elements.captchaForm.listeners.submit(event);assert.equal(checkCount(),n+1);
vm.runInContext("errors.visa=friendlyError(new Error('OCR.space HTTP 401 API key'));delete current.visa;renderResult('visa');",context);assert(!elements.visaResult.innerHTML.includes('OCR.space'));assert(!elements.visaResult.innerHTML.includes('API key'));
// Upstream failures must not be presented as a CAPTCHA typo, including HTML
// errors generated by the hosting platform. Retry preserves the successful source.
for(const failure of [{code:'SOURCE_UNAVAILABLE',error:'upstream busy'},{code:'SOURCE_ACCESS_BLOCKED',error:'blocked'},{code:'SOURCE_SESSION_EXPIRED',error:'expired',needsNewCaptcha:true},{html:true}]){elements.newApplication.onclick();visaError=failure;await start();await elements.captchaForm.listeners.submit(event);assert(!elements.visaResult.innerHTML.includes('ক্যাপচা মিলিয়ে'));assert(elements.ivacResult.innerHTML.includes('Ready For Delivery'));const beforeRetry=checkCount();visaError=null;await elements.retryCaptcha.onclick();assert.equal(checkCount(),beforeRetry);await elements.captchaForm.listeners.submit(event);assert.equal(checkCount(),beforeRetry+1);}
elements.newApplication.onclick();ocrExpired=true;await start();assert(elements['error-visa'].textContent.includes('সময় শেষ'));assert.equal(vm.runInContext('sessions.visa',context),undefined);assert(!elements['error-visa'].textContent.includes('নিজে লিখুন'));ocrExpired=false;
elements.newApplication.onclick();configFail=true;const beforeFailure=calls.filter(c=>c.path==='/api/prepare').length;await start();assert.equal(calls.filter(c=>c.path==='/api/prepare').length,beforeFailure+2);assert.equal(elements.confirmBtn.disabled,false);assert(!calls.some(c=>c.path==='/api/config'));configFail=false;
elements.resultNewApplication.onclick();assert.equal(elements.passportNo.value,'A12345678');assert.equal(elements.applicationId.value,'BGDABCDEFGHI1');assert.equal(elements.app.dataset.phase,'entry');assert(!elements.introHero.classList.contains('hidden'));assert(!elements.flowSteps.classList.contains('hidden'));assert.equal(elements.saveResults.disabled,true);assert(writes.every(([key,value])=>key==='visadesk.recentInputs'&&JSON.parse(value).every(row=>Object.keys(row).sort().join(',')==='applicationId,passportNo')));
vm.runInContext("for(let i=0;i<10;i++)rememberDetails({applicationId:'BGDRECENT00'+i,passportNo:'R123450'+i});rememberDetails({applicationId:'BGDRECENT009',passportNo:'R1234509'});",context);assert.equal(JSON.parse(storage.get('visadesk.recentInputs')).length,8);assert.equal(JSON.parse(storage.get('visadesk.recentInputs'))[0].applicationId,'BGDRECENT009');elements.applicationId.value='bgdrecent009';elements.applicationId.listeners.input({target:elements.applicationId});assert.equal(elements.applicationId.value,'BGDRECENT009');assert(elements.recentSuggestionsList.innerHTML.includes('BGDRECENT009'));assert(!elements.recentSuggestionsList.innerHTML.includes('BGDRECENT008'));elements.applicationId.listeners.keydown({key:'Escape'});assert(elements.recentSuggestions.classList.contains('hidden'));elements.passportNo.value='R1234508';elements.passportNo.listeners.focus();assert(elements.recentSuggestionsList.innerHTML.includes('BGDRECENT008'));assert(!elements.recentSuggestionsList.innerHTML.includes('BGDRECENT009'));documentListeners.click({target:elements.checkBtn});assert(elements.recentSuggestions.classList.contains('hidden'));elements.recentSuggestionsList.listeners.click({target:{closest:selector=>selector==='[data-remove-recent]'?{dataset:{removeRecent:'0'}}:null}});assert.equal(JSON.parse(storage.get('visadesk.recentInputs')).length,7);elements.clearRecents.onclick();assert(!storage.has('visadesk.recentInputs'));assert(elements.recentSuggestions.classList.contains('hidden'));vm.runInContext("localStorage.setItem=()=>{throw new Error('blocked')};rememberDetails({applicationId:'BGDRECENT001',passportNo:'R1234501'});",context);
console.log('PASS: explicit CAPTCHA review and correction before submission, expired/rejected image re-confirmation, status explanations, delivery steps, theme toggle, real completed-task progress, PNG download content and result header visibility, paired local suggestions, filtering, deduplication, deletion and storage failure fallback; no saved results or provider details.');
