import {existsSync} from 'node:fs';
import {loadLocalEnv,envPath} from './env.mjs';
import {resolveOCRProvider} from '../src/ocr-config.js';
const {env,exists}=loadLocalEnv();
console.log('Settings file: '+envPath);
console.log('.env.local: '+(exists?'FOUND':'MISSING — run npm run setup'));
if(existsSync(envPath+'.txt'))console.log('WARNING: .env.local.txt found. Windows may have saved the wrong extension.');
const provider=resolveOCRProvider(env);
console.log('OCR provider: '+provider);
if(provider==='gemini')console.log('OCR.space backup: '+(env.OCR_SPACE_API_KEY?.trim()?'SET (Gemini runs first)':'NOT SET'));
console.log('GEMINI_API_KEY: '+(env.GEMINI_API_KEY?.trim()?'SET (value hidden)':'NOT SET — optional; npm run configure-gemini'));
console.log('OCR_SPACE_API_KEY: '+(env.OCR_SPACE_API_KEY?.trim()?'SET (value hidden)':'NOT SET — optional; npm run configure-ocr'));
const keyName={gemini:'GEMINI_API_KEY','ocr-space':'OCR_SPACE_API_KEY',openai:'OPENAI_API_KEY'}[provider];
if(keyName&&!env[keyName]?.trim())console.log('WARNING: selected provider requires '+keyName+'.');
if(provider==='invalid')console.log('WARNING: OCR_PROVIDER must be auto, gemini, ocr-space, openai or browser.');
if(provider==='gemini')console.log('Gemini model setting: '+(!env.GEMINI_MODEL?.trim()||/^gemini-[A-Za-z0-9][A-Za-z0-9._-]{0,99}$/.test(env.GEMINI_MODEL.trim())?'VALID':'INVALID'));
console.log('Session encryption key: '+(/^[A-Za-z0-9_-]{43}$/.test(env.SESSION_ENCRYPTION_KEY||'')?'SET':'MISSING or invalid — run npm run setup'));
console.log('Restart the server after changes. On Vercel, set dashboard Environment Variables and Redeploy.');
